version: '2'
services: 
  build:
    build: .

  web:
    images: ubuntu
    links:
      - mysql
    ports:
      - "8000:80"
    environment:
      DB_HOST: mysql:3306
      DB_PASSWD: root

  mysql:
    images: mysql
    environment:
      - DB_PASSWD=root
    expose: #only for container without host
      - "3306"
    volumes:
      - /var/lib/mysql
      - cache/:/tmp/cache
      - ~/configs:/etc/configs/:ro
    dns:
      - 8.8.8.8
      - 9.9.9.9